export const models = {
  'Astral Shard': [
    { name: 'Dark Soul', rarity: 0.8 },
    { name: 'Elven Might', rarity: 0.8 },
    { name: 'Eve’s Apple', rarity: 0.8 },
    { name: 'Excalibrite', rarity: 1.3 },
    { name: 'Lovestone', rarity: 1.3 },
    { name: 'Aquarium', rarity: 1.3 },
    { name: 'Muffin', rarity: 1.3 },
    { name: 'Nectarite', rarity: 1.3 },
    { name: 'Crystal Punk', rarity: 1.3 },
    { name: 'Fractured', rarity: 1.7 },
    { name: 'Barbed', rarity: 1.7 },
    { name: 'Blender', rarity: 1.7 },
    { name: 'Ivy Vine', rarity: 1.7 },
    { name: 'Arctite', rarity: 1.7 },
    { name: 'Gold 999', rarity: 2 },
    { name: 'Premium', rarity: 2 },
    { name: 'Silver Art', rarity: 2 },
    { name: 'Gramite', rarity: 2 },
    { name: 'Jurassic', rarity: 2 },
    { name: 'Galactite', rarity: 2 },
    { name: 'Nouveau Gold', rarity: 2 },
    { name: 'Pure Silver', rarity: 2 },
    { name: 'Bogartite', rarity: 2 },
    { name: 'Warholite', rarity: 2 },
    { name: 'Uranium', rarity: 2 },
    { name: 'Moonstone', rarity: 2.3 },
    { name: 'RGB-ite', rarity: 2.3 },
    { name: 'Glowstone', rarity: 2.3 },
    { name: 'White Opal', rarity: 2.3 },
    { name: 'True Opal', rarity: 2.3 },
    { name: 'Black Diamond', rarity: 2.3 },
    { name: 'Labradorite', rarity: 2.3 },
    { name: 'Emerald', rarity: 2.4 },
    { name: 'Sapphire', rarity: 2.4 },
    { name: 'Ammolite', rarity: 2.4 },
    { name: 'Amethyst', rarity: 2.4 },
    { name: 'Ethereal', rarity: 2.4 },
    { name: 'Ocean Jasper', rarity: 2.4 },
    { name: 'Tourmaline', rarity: 2.4 },
    { name: 'Garnet', rarity: 2.4 },
    { name: 'Candy Flossite', rarity: 2.4 },
    { name: 'Bouquet', rarity: 2.4 },
    { name: 'Ruby Fuchsite', rarity: 2.4 },
    { name: 'Aquamarine', rarity: 2.4 },
    { name: 'Red Ruby', rarity: 2.4 },
    { name: 'Citrine', rarity: 2.4 },
    { name: 'Moonlit', rarity: 2.4 },
    { name: 'Sunstone', rarity: 2.4 },
    { name: 'Spinel', rarity: 2.4 },
    { name: 'Tanzanite', rarity: 2.4 },
  ],
}
